Upgrade upload-artifact to v4

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,8 +17,9 @@ jobs:
         uses: actions/checkout@v4
       
       - name: Create .env file
+        shell: bash
         run: |
-          echo "VITE_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
+          echo "VITE_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" > .env
           echo "VITE_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
           echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
           echo "VITE_FIREBASE_MEASUREMENTID=${{ secrets.FIREBASE_MEASUREMENTID }}" >> .env
@@ -29,10 +30,12 @@ jobs:
           echo "VITE_GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" >> .env
 
       - name: Verify .env file
-        run: cat .env
+        run: |
+          ls -la
+          cat .env || echo "⚠️ .env file NOT FOUND!"
 
       - name: Persist .env file
         uses: actions/upload-artifact@v4
         with:
           name: env-file
-          path: .env
+          path: ${{ github.workspace }}/.env
